/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_duckdb_DuckDBNative */

#ifndef _Included_org_duckdb_DuckDBNative
#define _Included_org_duckdb_DuckDBNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_startup
 * Signature: ([BZLjava/util/Properties;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1startup
  (JNIEnv *, jclass, jbyteArray, jboolean, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_connect
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1connect
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_set_auto_commit
 * Signature: (Ljava/nio/ByteBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1set_1auto_1commit
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_get_auto_commit
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1get_1auto_1commit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_disconnect
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1disconnect
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_set_schema
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1set_1schema
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_set_catalog
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1set_1catalog
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_get_schema
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1get_1schema
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_get_catalog
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1get_1catalog
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_prepare
 * Signature: (Ljava/nio/ByteBuffer;[B)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1prepare
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_release
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1release
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_query_result_meta
 * Signature: (Ljava/nio/ByteBuffer;)Lorg/duckdb/DuckDBResultSetMetaData;
 */
JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1query_1result_1meta
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_prepared_statement_meta
 * Signature: (Ljava/nio/ByteBuffer;)Lorg/duckdb/DuckDBResultSetMetaData;
 */
JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1prepared_1statement_1meta
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_execute
 * Signature: (Ljava/nio/ByteBuffer;[Ljava/lang/Object;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1execute
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_free_result
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1free_1result
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_fetch
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)[Lorg/duckdb/DuckDBVector;
 */
JNIEXPORT jobjectArray JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1fetch
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_fetch_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1fetch_1size
  (JNIEnv *, jclass);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_arrow_stream
 * Signature: (Ljava/nio/ByteBuffer;J)J
 */
JNIEXPORT jlong JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1arrow_1stream
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_arrow_register
 * Signature: (Ljava/nio/ByteBuffer;J[B)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1arrow_1register
  (JNIEnv *, jclass, jobject, jlong, jbyteArray);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_create_appender
 * Signature: (Ljava/nio/ByteBuffer;[B[B)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1create_1appender
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_begin_row
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1begin_1row
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_end_row
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1end_1row
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_flush
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1flush
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_interrupt
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1interrupt
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_close
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_append_boolean
 * Signature: (Ljava/nio/ByteBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1boolean
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_append_byte
 * Signature: (Ljava/nio/ByteBuffer;B)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1byte
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_append_short
 * Signature: (Ljava/nio/ByteBuffer;S)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1short
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_append_int
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1int
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_append_long
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1long
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_append_float
 * Signature: (Ljava/nio/ByteBuffer;F)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1float
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_append_double
 * Signature: (Ljava/nio/ByteBuffer;D)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1double
  (JNIEnv *, jclass, jobject, jdouble);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_append_string
 * Signature: (Ljava/nio/ByteBuffer;[B)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1string
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_append_timestamp
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1timestamp
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_append_decimal
 * Signature: (Ljava/nio/ByteBuffer;Ljava/math/BigDecimal;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1decimal
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_appender_append_null
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1null
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_create_extension_type
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1create_1extension_1type
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_duckdb_DuckDBNative
 * Method:    duckdb_jdbc_register_scalar_func
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Ljava/lang/String;Ljava/lang/reflect/Method;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1register_1scalar_1func
  (JNIEnv *, jclass, jobject, jstring, jstring, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
